config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :products do
    resources :reviews
  end

  resources :companies
  root 'products#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
       user ||= User.new # guest user (not logged in)
       if user.admin?
         can :manage, :all
       elsif user.sign_in_count? # registered user
         can :read, :all
         can [:update, :destroy], Review, :user_id => user.id
         can :create, Review
         can [:create, :update], Product
         can [:create, :update], Company
       else
         can :read, :all
       end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :products
  validates :name, presence: true
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :reviews, dependent: :destroy
  belongs_to :company
  validates :name, presence: true
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :product
  acts_as_taggable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  #before_action :authenticate_user!
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
  	@companies = Company.all
  end

  def show
	  @company = Company.find(params[:id])
  end

  def new
    @company = Company.new
  end

  def create
    @company = Company.new(company_params)
    if @company.save
      redirect_to @company
    else
      render 'new'
    end
  end

  def edit
    @company = Company.find(params[:id])
  end

  def update
    @company = Company.find(params[:id])
    if @company.update(company_params)
      redirect_to @company
    else
      render 'edit'
    end
  end

  def delete
    @company = Company.find(params[:id])
  end

  def destroy
    @company = Company.find(params[:id])
    @company.destroy

    redirect_to companies_path
  end

  private
  def company_params
	  params.require(:company).permit(:name, :description)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  load_and_authorize_resource

  def new
    @product = Product.new
    @companies = Company.all
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to @product
    else
      render 'new'
    end
  end

  def show
    @product = Product.find(params[:id])
    @tag_counts = @product.reviews.tag_counts
  end

  def index
    @products = Product.all.sort_by { |p| [p.name] }
    @tag_counts = Review.tag_counts
  end

  def edit
    @product = Product.find(params[:id])
    @companies = Company.all
  end

  def update
    @product = Product.find(params[:id])

    if @product.update(product_params)
      redirect_to @product
    else
      render 'edit'
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    redirect_to products_path
  end

  private
    def product_params
      params.require(:product).permit(:name, :description, :company_id)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.create(review_params)
    @review.update_attribute :user_id, current_user.id
    redirect_to product_path(@product)
  end

  def destroy
    @product = Product.find(params[:product_id])
    @review = @product.reviews.find(params[:id])
    @review.destroy
    redirect_to product_path(@product)
  end

  private
    def review_params
      params.require(:review).permit(:reviewer, :text, :user_id, :tag_list => [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/acts_as_taggable_on/tags/_tag.html.erb
<li>
  <%= tag.name %>
  <span class="badge">
    <%= tag.count %>
  </span>
</li>

app/views/companies/_form.html.erb
<%= form_for @company do |c| %>
  <% if @company.errors.any? %>
  <div class="alert alert-info">
    <strong><%= pluralize(@company.errors.count, "error") %>:</strong>
    <ul>
    <% @company.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <div class="form-group">
    <%= c.label :name %><br>
    <%= c.text_field :name %>
  </div>
  
  <div class="form-group">
    <%= c.label :description %><br>
    <%= c.text_area :description %>
  </div>

  <input type="submit" value="Submit" class="btn btn-success" />
  <%= link_to 'Back', companies_path, class: 'btn btn' %>

<% end %>

app/views/companies/edit.html.erb
<h2>Editing company</h2>

<% if can? :destroy, @company %>
  <%= link_to 'Delete', @company , class: 'btn btn-sm btn-danger',
      method: :delete, data: { confirm:  'Are you sure?' } %>
<% end %>

<%= render 'form'  %>

app/views/companies/index.html.erb
<div class="row">
  <h2>Company listing
    <% if can? :create, Company %>
     <%= link_to 'Add new company', new_company_path, class: 'btn btn-success' %>
    <% end %>
  </h2>
</div>

<div class="company-listing">
  <% @companies.each do |c| %>
    <div class="row">
      <div class="row">
        <h3><%= link_to c.name, company_path(c) %>
        <% if can? :update, c %>
        <%= link_to 'Edit', edit_company_path(c), class: 'btn btn-sm btn-warning' %>
        <% end %>
        <% if can? :destroy, c %>
        <%= link_to 'Delete', company_path(c), class: 'btn btn-sm btn-danger',
            method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
        </h3>
      </div>
      <p><%= c.description %></p>
    </div>
  <% end %>
</div>

app/views/companies/new.html.erb
<h3>New Company</h3>

<%= render 'form' %>

app/views/companies/show.html.erb
<%= link_to 'Back to company listing', companies_path %>

<div class="company-listing">
  <div class="row">
    <h3>
      <%= @company.name %>
      <% if can? :update, @company %>
        <%= link_to 'Edit', edit_company_path(@company), class: "btn btn-sm btn-warning" %>
      <% end %>
      
    </h3>
    <p><%= @company.description %></p>
  </div>

  <h4>Products</h4>
  <ul>
    <% @company.products.each do |product| %>
      <li> <%= link_to product.name, product_path(product) %> </li>
    <% end %>
  </ul>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EmotionReviews</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <div class="page-header">
    <div class="row">
      <div class="col-md-6">
        <h1><%= link_to "Emotion Reviews" ,root_path %></h1>
        <p>Real product reviews based on real human emotions.</p>
      </div>
      <div class="col-md-2"></div>
      <div class="col-md-4">
        <% if user_signed_in? %>
        <p>
          Logged in as <strong><%= current_user.email %></strong>.
        </p>
        <p>
          <%= link_to 'Edit profile', edit_user_registration_path %> |
          <%= link_to "Logout", destroy_user_session_path, method: :delete %>
        </p>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path %> |
          <%= link_to "Login", new_user_session_path %>
        <% end %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <%= link_to "Products", products_path %>
        <%= link_to "Companies", companies_path %>
      </div>
    </div>
  </div>


<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<%= yield %>

<div class="mastfoot">
  <div class="inner">
    <p>
      (C) 2014 Teemu Frisk
      <%= link_to '@teemu_f', 'https://twitter.com/teemu_f' %>
    </p>
  </div>
</div>
</div>
</body>
</html>

app/views/products/_form.html.erb
<%= form_for @product do |f| %>
  <% if @product.errors.any? %>
  <div class="alert alert-info">
    <strong><%= pluralize(@product.errors.count, "error") %>:</strong>
    <ul>
    <% @product.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  
  <div class="form-group">
    <%= f.label :company %><br>

    <% if !@companies.nil? %>
      <%= f.select :company_id, options_for_select(@companies.collect { |company|
      [company.name.titleize, company.id] }, @product.company_id), {}, { id: 'companies_select' } %>
    <% else %>
      No companies defined. Please create companies first before assigning them to products.
    <% end %>
  </div>
  
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

  <input type="submit" value="Submit" class="btn btn-success" />
  <%= link_to 'Back', products_path, class: 'btn btn' %>

<% end %>

app/views/products/edit.html.erb
<h2>Editing product</h2>

<% if can? :destroy, @product %>
  <%= link_to 'Delete', @product , class: 'btn btn-sm btn-danger',
      method: :delete, data: { confirm:  'Are you sure?' } %>
<% end %>

<%= render 'form'  %>

app/views/products/index.html.erb
<div class="row">
  <h2>Product listing
    <% if can? :create, Product %>
     <%= link_to 'Add new product', new_product_path, class: 'btn btn-success' %>
    <% end %>
  </h2>
</div>

<p><strong>Emotions:</strong>
  <ul class="nav nav-pills">
    <%= render @tag_counts.sort_by { |t| [-t.count, t.name] } %>
  </ul>
</p>

<div class="product-listing">
  <% @products.each do |p| %>
    <div class="row">
      <div class="row">
        <h3><%= link_to p.name, product_path(p) %>
        <% if can? :update, p %>
        <%= link_to 'Edit', edit_product_path(p), class: 'btn btn-sm btn-warning' %>
        <% end %>
        <% if can? :destroy, p %>
        <%= link_to 'Delete', product_path(p), class: 'btn btn-sm btn-danger',
            method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
        </h3>
      </div>
      <p><%= p.description %></p>
    </div>
  <% end %>
</div>

app/views/products/new.html.erb
<h3>New Product</h3>

<%= render 'form' %>

app/views/products/show.html.erb
<%= link_to 'Back to product listing', products_path %>

<div class="product-listing">
  <div class="row">
    <h3>
      <%= @product.name %>
      <% if can? :update, @product %>
        <%= link_to 'Edit', edit_product_path(@product), class: "btn btn-sm btn-warning" %>
      <% end %>
      
    </h3>
    <% if @product.company %>
      <p><%= link_to @product.company.name, company_path(@product.company_id) %></p>
    <% end %>
    <p><%= @product.description %></p>
  </div>

<p>
  <strong>Emotions:</strong>
  <ul class="nav nav-pills">
    <%= render @tag_counts.sort_by { |t| [-t.count, t.name] } %>
  </ul>
</p>


<div class="row">
  <h3>Reviews</h3>
</div>
<%= render @product.reviews %>


<% if can? :create, Review %>
  <h4>Add a review:</h4>
  <%= render "reviews/form" %>
<% else %>
  <p><%= link_to 'Login', new_user_session_path %> to add a review</p>
<% end %>

</div>

app/views/reviews/_form.html.erb
<%= form_for([@product, @product.reviews.build]) do |f| %>
  <div class="form-group">
    <%= f.label :reviewer %><br>
    <%= f.text_field :reviewer %>
  </div>
  <div class="form-group">
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </div>
  <div class="form-group">
    <%= f.label :tag_list, "Emotions" %><br>
    <%= f.select :tag_list,
        # Plutchik's wheel of emotions
        options_for_select(["joy", "trust", "fear", "surprise", "sadness", "disgust", "anger", "anticipation"]),
        {}, {:multiple => true, :class => "tag-select"} %>
  </div>

  <input type="submit" value="Submit" class="btn btn-success" />
  <%= link_to 'Back', products_path, class: 'btn btn' %>

<% end %>

app/views/reviews/_review.html.erb
<div class="row">

<h4>
  <%= review.reviewer %>
  <% if can? :destroy, review %>
    <%= link_to 'Delete',
      [review.product, review],
        class: "btn btn-xs btn-danger",
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
  <% end %>
</h4>

<p>
  <%= review.text %>
</p>

<p>
  <ul class="nav nav-pills">
    <% review.tag_list.each do |t| %>
      <li> <%= t %> </li>
    <% end %>
  </ul>
</p>

</div>

app/views/welcome/index.html.erb
<h1>Emotion Reviews</h1>

<%= link_to 'Product Reviews', controller: 'products' %>